name: jbaza
description: Jbaza is a state management package, a simplified and modified version of the Stacked package
version: 0.1.5
homepage: https://github.com/Javoh29/Jbaza.git

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  meta: ^1.7.0
  flutter_hooks: ^0.18.2+1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  sentry_flutter: ^6.3.0
  device_info: ^2.0.3
  path_provider: ^2.0.9
  share: ^2.0.4
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
