name: jbaza
description: Jbaza is a state management package, a simplified and modified version of the Stacked package
version: 0.1.6
homepage: https://github.com/Javoh29/Jbaza.git

environment:
  sdk: ">=2.16.0 <3.3.1"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  meta: ^1.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sentry_flutter: ^7.4.2
  device_info_plus: ^8.2.0
  path_provider: ^2.0.14
  share_plus: ^6.3.2
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
